/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\WallFloor.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/WallFloor.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Plane_1"
        geometry={nodes.Plane_1.geometry}
        material={materials.Floor}
      />
      <mesh
        name="Plane_2"
        geometry={nodes.Plane_2.geometry}
        material={materials.Default}
      />
      <mesh
        name="Plane_3"
        geometry={nodes.Plane_3.geometry}
        material={materials.Wall}
      />
    </group>
  );
}

useGLTF.preload("/WallFloor.glb");
