/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\Shelf.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export function Shelf(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/Shelf.glb");
  return (
    <group {...props} dispose={null}>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 0.049 : 0,
        }}
        name="Node"
        position={[-0.964, 1.963, -1.947]}
      >
        <mesh
          name="Node-Mesh001"
          geometry={nodes["Node-Mesh001"].geometry}
          material={materials.lambert4SG}
        />
        <mesh
          name="Node-Mesh001_1"
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={materials["lambert2SG.001"]}
        />
        <mesh
          name="Node-Mesh001_2"
          geometry={nodes["Node-Mesh001_2"].geometry}
          material={materials["lambert3SG.001"]}
        />
      </motion.group>
      <motion.mesh
        name="Astronaut_mesh"
        geometry={nodes.Astronaut_mesh.geometry}
        material={materials.Astronaut_mat}
        position={[0.24, 1.908, -1.959]}
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 0.095 : 0,
        }}
      />
      <group
        name="SM_ShelfSM_Shelf1"
        position={[-0.383, 1.614, -2.069]}
        scale={0.499}
      >
        <mesh
          name="SM_ShelfSM_Shelf1_1001"
          geometry={nodes.SM_ShelfSM_Shelf1_1001.geometry}
          material={materials["lambert2SG.002"]}
        />
        <mesh
          name="SM_ShelfSM_Shelf1_1001_1"
          geometry={nodes.SM_ShelfSM_Shelf1_1001_1.geometry}
          material={materials["lambert3SG.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/Shelf.glb");
